@startuml
class Actividades {
 -int _codactividad
 -String _nombre
 -String _descripcion
 -String _responsable
 -double _horas
 -int _valoracion
 -Docentes _coddocente
 -TipoModalidades _codtipo
 +Actividades getCampo()
 +void agregar()
 +List<Actividades> getListado()
 +void borrar(Actividades faceObj)
 +void actualizar()
 +double acumHorasPorTipo(int tipo)
}

class Asignacion {
 -int _codasg
 -Docentes _coddocente
 -Coordinacion _codcoordinacion
 -Double _horasclase
 -Double _preparacion
 -Double _capacitacion
 -Double _colectivo
 -Double _investigacion
 -Double _social
 -Double _oda
 -Double _planeacion
 -Double _virtualidad
 -Double _comites
 -Double _sumatoria
 +double getCalculate(Asignacion asigTemp)
 +List<Asignacion> getListadoAsign()
 +String checkSum(double sum, int tipo)
 +void actualizar(Asignacion obj) 
}

class Coordinacion {
 -int _codcoordinacion
 -String _nombre
 -Double _investigacion
 -Double _extension
 -Double _comites
 -Double _oda
 -Double _acreditacion
 -Double _virtualidad
 -boolean _asignado
 -Facultad _codfacultad
 +Coordinacion getCampo()
 +List<Coordinacion> getListado()
 +void procesar()
 +void agregar()
 +void borrar(Coordinacion faceObj) 
 +void actualizar()
}

class Docentes {
 -int _cedula
 -String _nombres
 -String _apellidos
 -String _codigo
 -String _direccion
 -String _telefono
 -String _correo
 -String _foto
 -Coordinacion _codcoordinacion
 -String _formacion
 -int _tipocontrato
 -Date _fechanac
 -String celular
 -int tipo_doc
 -String lugar_exp
 -String municipio
 -String lugar_nac
 -int genero
 -Date fecha_exp
 -String matricula_prof
 -String _nombreCoord
 -int _inhabilitar
 -int _tipo_usuario
 +Docentes getCampo()
 +void agregar()
 +List<Docentes> getListado()
 +void actualizar()
 +void configurarAsignacion(int tipoContrato)
 +Docentes buscar()
}

class Experiencia {
 -int cod_experiencia
 -int tiempo
 -String institucion
 -String actividad
 -String dependencia
 -String tipo_contrato
 -int tipo
 -Date fecha_ultima
 -Docentes coddocente
 +Experiencia getCampo()
 +void agregar()
 +List<Experiencia> getListado()
 +void borrar(Experiencia faceObj)
 +void actualizar()
}

class Facultad {
 -int _codfacultad
 -String _nombre
 -String _abreviatura
 +Facultad getCampo()
 +List<Facultad> getListado()
 +void agregar()
 +void actualizar()
 +void borrar(Facultad faceObj)
}

class Facultad {
 -int _codfacultad
 -String _nombre
 -String _abreviatura
 +Facultad getCampo()
 +List<Facultad> getListado()
 +void agregar()
 +void actualizar()
 +void borrar(Facultad faceObj)
}
@enduml